### ISSUE TITLE
Sql Error: Field doesn't have a default value, when Super & Child share a column

### ISSUE THREAD

**Issue by madsem** [dive-be/eloquent-super#2]
Hey,

thanks for this package, works like a charm so far.
But I'm running into an issue where I'm getting data from a third-party API and have the save the `remote_id` field on the `Super` model as well as the `Child`.

When try to do an `updateorCreate` I get the following exception:
```log
SQLSTATE[HY000]: General error: 1364 Field 'remote_id' doesn't have a default value
```

Both of my models have a `$fillable` set with the `remote_id`.

This is how I prep the data
```php
$campaigns
                    ->map(function ($campaign) {

                        return [
                            'attributes' => [
                                'remote_id' => $campaign['id'],
                            ],
                            'values' => [

                                // Saved to Campaign
                                'name' => $campaign['name'],
                                'user_id' => $this->account->user_id,
                                'account_id' => $this->account->id,

                                // remote_id is saved to Campaign & GoogleCampaign
                                'remote_id' => $campaign['id'],
...
...
```

to be updated or created:
```php
->each(function ($campaign) {

                        GoogleCampaign::updateOrCreate(
                            $campaign['attributes'],
                            $campaign['values']
                        );
                    });
```

Imho this `should` work but I believe that `Super` removes the `remote_id` because it doesn't expect that the same field could be used in both models...?

**Comment by mabdullahsari** [comment]
Hello! 👋
Sorry that this took a little long; have been really busy last month.

Your remark is correct. There shouldn't be ambiguous column names in both tables.
The package makes a simple assumption that the sub tables will always *complement* the super tables i.e. your `Campaign` model should be the **only** model that has the `remote_id` column. There is a note at the bottom of the readme that says that the `super` relationships is always eager loaded. Whenever you fetch a `GoogleCampaign`, you will automatically have a `remote_id` anyways inherited from the `super` relationship.

If you keep the columns in both tables for query performance reasons, then I'm afraid there is nothing that can be done by me to solve this ambiguity. There is no way for me to know which table you will be targeting when setting those values.
You will have to explicitly set those values.

Hope this answers your question.
